struct devent {
	double time;
	int popi;
	int popj;
	double paramv;
	double **mat ;
	char detype ;
	struct devent *nextde;
	} ;
	
struct c_params {
	int npop;
	int nsam;
	int *config;
	double **mig_mat;
	double r;
	int nsites;
	double f;
	double track_len;
	double *size;
	double *alphag;
	struct devent *deventlist ;
	} ;
	
struct m_params {
	 double theta;
	int segsitesin;
	int treeflag;
        int treelengthflag;
	int mfreq;
	 } ;
	 
struct params { 
	struct c_params cp;
	struct m_params mp;
	int commandlineseedflag ;
	};

/*voy a declarar una estructura donde voy a guardar todas las variables que tengan algo que ver con los estadísticos del rejection algorithm */
struct rejection_statistics{
int rejectionflag;
float fractionsites;
float randomnumber; 
int hcounter,micronumber;
float sitebeginning;
float sitethreshold;
int flagbegin;
int flagthreshold;
signed int *microsegsite;
int **microsize;
float *mean;
float *variance;
float sum;
float squaresum;
float rejectionvariance;
int *microflag;
float *heterozygosis;
float homopart,heterozygosismean;
int configflag;
int numberconfigurations;
float **frecalelo;
float pij;
float D,Dsquared;
float **denominatorsquare;
int counterfreq;
double ld_denominator;
double delta;
float *kurtosis;
float kurtomean;
float varofvar;
float totallinkage;
float denominator;
int segtajd;
int flag;
int *maxsize;
int *minsize;
int thetavaluesnum;
float *thetavalues;
int variablethetaflag;
int *differencepairs,pairmaximum;
float *frequencypairs;
float pairmean;
float kurtonumerator;
float kurtodenominator;
float skewnumerator;
float skewdenominator;
float pi;
float modefreq;
int mode;
float freqsum;
float difmeanmedian;
float difmeanmode;
float difmodemedian;
int segsitemic;
int micromax;
int micromin;
int infinitesegsites;
char **infinitesegpart;
float infinitesegcounter;
char *sitepart;
char *sitepart2;
float ispi;
float infiniteheterozygosis;
int subpop;
int *popsize;
int **datamicrosize;
float dataheterozygosis;
float datavariancemean;
int datanumberofconfig, acceptances, readacceptances, simulationnumber;
char *simnum;
float dataFst, Fst;
float alpha;
float dif1,dif2,dif3,dif4;
int *configs, *hapnumber;
int *microminsize, *micromaxsize,segsitedif;
char ***infinitesitepart;
float *infinite_heterozygosis;
float *homoplasyloc;
float homoplasymeanloc;
char **microchain,**ISchain;
float SH,MASH,SASH,SHchanges,SHdist;
int segsites;
float sizehomoplasy1;
float HBC;
int ISconfigurations, simsites, simsingleton;
float simmicsegsites, simheterohap, simconfigmicvar;
float TMRCA;
float TempISMic, TempSMMMic, TempISDist, TempSMMDist, TempPIS, TempPSMM;
};
